### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by statulr**
Added Readme and first lua

Just something nice

Once code is up and going I will commit some stuff + I will edit the readme to have more stuff dw :)

### CODE REVIEW

**Comment by qtkittyy** [comment]
Already added stuff, and just updated the README

**Comment by statulr** [comment]
Hey lol, been a while

**Comment by qtkittyy** [comment]
Oh ye it has been! Hmm, how may I contact you?

**Comment by qtkittyy** [comment]
Hm! yea it has been

**Comment by statulr** [comment]
> Hm! yea it has been

Wait what happened your discord got deleted!?! Do you have a new discord?

**Comment by qtkittyy** [comment]
No I do not at the moment (maybe will in the future for advertising), but I am reachable over matrix @theofalltime:matrix.org

**Pull request closed without merging**
